import type { Database } from "../types/supabase";

type Product = Database["public"]["Tables"]["products"]["Row"];

// Simple text file generator instead of PDF to avoid memory issues
export const generateProductPDF = (product: Product) => {
  try {
    // Create a simple text representation of the product
    let content = [];

    // Title
    content.push(`# ${product.name}`);
    content.push("\n");

    // Description
    if (product.description) {
      content.push(product.description);
      content.push("\n");
    }

    // Basic details
    content.push(`Price: ${product.price.toFixed(2)}`);

    // Product Details
    if (product.features || product.color || product.gloss) {
      content.push("\n");
      content.push("## Product Details");

      if (product.features) {
        content.push(`Features: ${product.features}`);
      }

      if (product.color) {
        content.push(`Color: ${product.color}`);
      }

      if (product.gloss) {
        content.push(`Gloss: ${product.gloss}`);
      }
    }

    // Technical Specifications
    if (
      product.volume_solids ||
      product.voc ||
      product.theoretical_spreading_rate
    ) {
      content.push("\n");
      content.push("## Technical Specifications");

      if (product.volume_solids) {
        content.push(`Volume Solids: ${product.volume_solids}`);
      }

      if (product.voc) {
        content.push(`VOC: ${product.voc}`);
      }

      if (product.theoretical_spreading_rate) {
        content.push(
          `Spreading Rate: ${product.theoretical_spreading_rate} m²/L`,
        );
      }

      if (product.specific_gravity) {
        content.push(`Specific Gravity: ${product.specific_gravity}`);
      }
    }

    // Application Instructions
    if (product.method_of_application || product.mixing || product.thinner) {
      content.push("\n");
      content.push("## Application Instructions");

      if (product.method_of_application) {
        content.push(`Application Method: ${product.method_of_application}`);
      }

      if (product.mixing) {
        content.push(`Mixing Instructions: ${product.mixing}`);
      }

      if (product.thinner) {
        content.push(`Thinner: ${product.thinner}`);
      }
    }

    // Footer
    content.push("\n");
    content.push(
      "Generated by Décor Paint - For the most up-to-date information, please visit our website.",
    );

    // Join all content with line breaks
    const textContent = content.join("\n");

    // Create a blob and download it as a text file
    const blob = new Blob([textContent], { type: "text/plain;charset=utf-8" });
    const fileName = `${product.name.toLowerCase().replace(/\s+/g, "-")}-specifications.txt`;

    // Create a download link
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = fileName;
    link.style.display = "none";

    // Trigger download
    document.body.appendChild(link);
    link.click();

    // Clean up
    setTimeout(() => {
      URL.revokeObjectURL(url);
      document.body.removeChild(link);
    }, 100);
  } catch (error) {
    console.error("Error generating text file:", error);
  }
};
