import type { Database } from '../types/supabase';
import jsPDF from 'jspdf';

type Product = Database['public']['Tables']['products']['Row'];

export const generateProductPDF = (product: Product) => {
  const doc = new jsPDF();
  
  // Set initial position
  let y = 20;
  const margin = 20;
  const lineHeight = 7;
  
  // Helper function to add text and handle overflow
  const addText = (text: string, indent: number = 0) => {
    const lines = doc.splitTextToSize(text, doc.internal.pageSize.width - margin * 2 - indent);
    lines.forEach(line => {
      if (y > doc.internal.pageSize.height - margin) {
        doc.addPage();
        y = margin;
      }
      doc.text(line, margin + indent, y);
      y += lineHeight;
    });
    y += 3; // Add extra space after paragraph
  };
  
  // Helper function for section titles
  const addSectionTitle = (title: string) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    addText(title);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(12);
  };
  
  // Title and basic info
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  addText(product.name);
  
  doc.setFontSize(14);
  addText(`Price: $${product.price.toFixed(2)}`);
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  
  if (product.description) {
    y += 5;
    addText(product.description);
  }
  
  // Product Details
  if (product.features || product.color || product.gloss) {
    y += 5;
    addSectionTitle('Product Details');
    
    if (product.features) {
      addText('Features:', 0);
      addText(product.features, 10);
    }
    if (product.color) {
      addText(`Color: ${product.color}`, 10);
    }
    if (product.gloss) {
      addText(`Gloss: ${product.gloss}`, 10);
    }
  }
  
  // Technical Specifications
  if (product.volume_solids || product.voc || product.theoretical_spreading_rate) {
    y += 5;
    addSectionTitle('Technical Specifications');
    
    if (product.volume_solids) {
      addText(`Volume Solids: ${product.volume_solids}`, 10);
    }
    if (product.voc) {
      addText(`VOC: ${product.voc}`, 10);
    }
    if (product.theoretical_spreading_rate) {
      addText(`Spreading Rate: ${product.theoretical_spreading_rate} m²/L`, 10);
    }
    if (product.specific_gravity) {
      addText(`Specific Gravity: ${product.specific_gravity}`, 10);
    }
    if (product.flexibility) {
      addText(`Flexibility: ${product.flexibility}`, 10);
    }
    if (product.adhesion) {
      addText(`Adhesion: ${product.adhesion}`, 10);
    }
    if (product.washability) {
      addText(`Washability: ${product.washability}`, 10);
    }
    if (product.abrasion_resistance) {
      addText(`Abrasion Resistance: ${product.abrasion_resistance}`, 10);
    }
  }
  
  // Application Instructions
  if (product.method_of_application || product.mixing || product.thinner) {
    y += 5;
    addSectionTitle('Application Instructions');
    
    if (product.method_of_application) {
      addText(`Application Method: ${product.method_of_application}`, 10);
    }
    if (product.mixing) {
      addText(`Mixing Instructions: ${product.mixing}`, 10);
    }
    if (product.thinner) {
      addText(`Thinner: ${product.thinner}`, 10);
    }
    if (product.application_temperatures) {
      addText(`Application Temperature: ${product.application_temperatures}`, 10);
    }
    if (product.surface_preparation) {
      addText(`Surface Preparation: ${product.surface_preparation}`, 10);
    }
  }
  
  // Drying Time
  if (product.dry_to_touch || product.dry_to_handle || product.dry_to_topcoat) {
    y += 5;
    addSectionTitle('Drying Time');
    
    if (product.dry_to_touch) {
      addText(`Dry to Touch: ${product.dry_to_touch}`, 10);
    }
    if (product.dry_to_handle) {
      addText(`Dry to Handle: ${product.dry_to_handle}`, 10);
    }
    if (product.dry_to_topcoat) {
      addText(`Dry to Topcoat: ${product.dry_to_topcoat}`, 10);
    }
    if (product.complete_setting) {
      addText(`Complete Setting: ${product.complete_setting}`, 10);
    }
  }
  
  // Storage and Safety
  if (product.storing_conditions || product.notice) {
    y += 5;
    addSectionTitle('Storage and Safety');
    
    if (product.storing_conditions) {
      addText(`Storage Conditions: ${product.storing_conditions}`, 10);
    }
    if (product.notice) {
      addText(`Safety Notice: ${product.notice}`, 10);
    }
  }
  
  // Additional Notes
  if (product.note) {
    y += 5;
    addSectionTitle('Additional Notes');
    addText(product.note, 10);
  }
  
  // Footer
  doc.setFontSize(10);
  doc.setTextColor(100);
  const footer = 'Generated by Décor Paint - For the most up-to-date information, please visit our website.';
  const footerWidth = doc.getTextWidth(footer);
  doc.text(footer, (doc.internal.pageSize.width - footerWidth) / 2, doc.internal.pageSize.height - 10);
  
  // Save the PDF
  doc.save(`${product.name.toLowerCase().replace(/\s+/g, '-')}-specifications.pdf`);
};